### ISSUE TITLE
Do I need to install all the requirements if I'm using Helm?

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/charlescd-docs#6]
In the `[Installing via Helm](https://docs.charlescd.io/get-started/installing-charles/installing-via-helm)` there is the paragraph:
Before proceeding, make sure that all the requirements are properly installed.

> However, there is a Requisites section in the line below only with two applications (Kubernetes and Helm).

Once Helm manages the package application to Kubernetes. Do I really to install something besides Kubernetes and Helm?

**Comment by barbararochazup** [comment]
Hi @otaviojava

We updated the pre-requesites doc section https://docs.charlescd.io/get-started/installing-charles#requirements

Today besides Kubernetes and Helm it's necessary install Istio, because Charles use Istio to traffic routing.

**Ref.** https://docs.charlescd.io/get-started/installing-charles#requirements

In addition to that, If you would like use metrics modules it's necessary install Prometheus

**Ref.** https://docs.charlescd.io/reference/metrics/setting-up-your-metrics#istio-configuration
